name: news_app
description: "News App with TDD, clean architecture"

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

  


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dartz:
  json_annotation: ^4.9.0
  http: ^1.2.2
  sqflite: ^2.3.3+1
  data_connection_checker_tv: ^0.3.5-nullsafety
  path: ^1.9.0
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true